server:
  port: 8766
spring:
  application:
    name: server-zull
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVER-RIBBON
    api-b:
          path: /api-b/**
          serviceId: SERVER-FEGIN
